name: Broken Lint Commenter

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commenter:
    name: Lint Commenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup-node
      - run: pnpm install --frozen-lockfile
      - run: pnpm ci:eslint
      - if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.COMMENTER_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "@${{ github.event.pull_request.user.login }}, Please run `pnpm ci:eslint -- --fix` on root to fix eslint error."
            })
